# Generated by Django 4.2.9 on 2025-09-03 03:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transportation'), ('energy', 'Energy'), ('food', 'Food'), ('waste', 'Waste'), ('other', 'Other')], max_length=20)),
                ('amount', models.FloatField(help_text='Carbon footprint in kg CO2')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CarbonGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.FloatField(help_text='Target carbon footprint in kg CO2 per month')),
                ('current_amount', models.FloatField(default=0, help_text='Current carbon footprint in kg CO2 this month')),
                ('month', models.DateField()),
                ('achieved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
