# Generated by Django 4.2.9 on 2025-09-03 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyCheckupResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                (
                    "appliance_usage",
                    models.CharField(
                        choices=[
                            ("NONE", "0"),
                            ("1-2", "1-2"),
                            ("3-5", "3-5"),
                            ("DAILY", "Daily"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "lighting_used",
                    models.CharField(
                        choices=[
                            ("LED", "All LED"),
                            ("MIXED", "Mixed"),
                            ("CFL", "Mostly CFL"),
                            ("INC", "Mostly incandescent"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "heating_ac_usage",
                    models.CharField(
                        choices=[
                            ("NONE", "0"),
                            ("1-2", "1-2"),
                            ("3-5", "3-5"),
                            ("DAILY", "Daily"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "car_usage",
                    models.CharField(
                        choices=[
                            ("NONE", "0"),
                            ("1-2", "1-2"),
                            ("3-5", "3-5"),
                            ("DAILY", "Daily"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "flights",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("SHORT", "Short"),
                            ("LONG", "Long"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "public_transport",
                    models.CharField(
                        choices=[
                            ("NONE", "0"),
                            ("1-2", "1-2"),
                            ("3-5", "3-5"),
                            ("DAILY", "Daily"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "compost_recycle",
                    models.CharField(
                        choices=[
                            ("NO", "No"),
                            ("SOME", "Some"),
                            ("DAILY", "Every day"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "secondhand_purchases",
                    models.CharField(
                        choices=[("NO", "No"), ("ONE", "1 item"), ("MANY", "2+ items")],
                        max_length=4,
                    ),
                ),
                ("weekly_raw_total", models.FloatField()),
                ("weekly_total", models.FloatField()),
                ("pct_change_from_last", models.FloatField(blank=True, null=True)),
                ("monthly_estimate", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InitialSurveyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                (
                    "household_size",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2-3"), (4, "4-5"), (6, "6+")]
                    ),
                ),
                (
                    "home_type",
                    models.CharField(
                        choices=[
                            ("APT", "Apartment"),
                            ("SEMI", "Semi-detached"),
                            ("DET", "Detached"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "primary_heating",
                    models.CharField(
                        choices=[
                            ("ELEC", "Electric"),
                            ("GAS", "Gas"),
                            ("OIL", "Oil"),
                            ("NONE", "None"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "appliance_use",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("OCCAS", "Occasionally"),
                            ("NEVER", "Never"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "lighting_type",
                    models.CharField(
                        choices=[
                            ("LED", "LED"),
                            ("CFL", "CFL"),
                            ("INC", "Incandescent"),
                            ("MIX", "Mixed"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "air_conditioning",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")], max_length=3
                    ),
                ),
                (
                    "car_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("PETROL", "Petrol"),
                            ("DIESEL", "Diesel"),
                            ("HYBRID", "Hybrid"),
                            ("ELEC", "Electric"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "device_time",
                    models.CharField(
                        choices=[
                            ("LT2", "<2h"),
                            ("2-4", "2-4h"),
                            ("4-8", "4-8h"),
                            ("GT8", "8+h"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "renewable_pct",
                    models.IntegerField(
                        choices=[
                            (0, "0%"),
                            (25, "25%"),
                            (50, "50%"),
                            (75, "75%"),
                            (100, "100%"),
                        ]
                    ),
                ),
                (
                    "flights_per_year",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("1SHORT", "1 short"),
                            ("2-4SHORT", "2-4 short"),
                            ("1LONG", "1 long"),
                            ("MULTLONG", "Multiple long"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "public_transport",
                    models.CharField(
                        choices=[
                            ("NEVER", "Never"),
                            ("OCCAS", "Occasionally"),
                            ("WEEKLY", "Weekly"),
                            ("DAILY", "Daily"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "compost_waste",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")], max_length=3
                    ),
                ),
                (
                    "clothes_drying",
                    models.CharField(
                        choices=[
                            ("LINE", "Always line"),
                            ("MIXED", "Sometimes"),
                            ("DRYER", "Always dryer"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "buy_secondhand",
                    models.CharField(
                        choices=[
                            ("OFTEN", "Often"),
                            ("SOME", "Sometimes"),
                            ("RARELY", "Rarely"),
                            ("NEVER", "Never"),
                        ],
                        max_length=6,
                    ),
                ),
                ("monthly_raw_total", models.FloatField()),
                ("home_electric_subtotal", models.FloatField()),
                ("renewable_discount", models.FloatField()),
                ("monthly_total", models.FloatField()),
                ("monthly_per_person", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
