# Generated by Django 4.2.22 on 2025-09-09 02:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_alter_userprofile_house_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="initialsurveyresult",
            name="home_type",
        ),
        migrations.RemoveField(
            model_name="initialsurveyresult",
            name="household_size",
        ),
    ]
