# Generated by Django 4.2.22 on 2025-09-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_remove_initialsurveyresult_home_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="appliance_usage",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="car_usage",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="compost_recycle",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="flights",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="heating_ac_usage",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="lighting_used",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="public_transport",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="secondhand_purchases",
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="car_type",
            field=models.CharField(
                choices=[
                    ("ELEC", "🚙 Electric"),
                    ("HYBRID", "🚗 Hybrid/small car"),
                    ("LARGE", "🛻 Large petrol/diesel"),
                ],
                default="MED",
                max_length=6,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="cooking_food",
            field=models.CharField(
                choices=[
                    ("LOW", "Low Impact"),
                    ("MED", "Medium Impact"),
                    ("HIGH", "High Impact"),
                ],
                default="MED",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="heating_cooling",
            field=models.CharField(
                choices=[
                    ("LOW", "Low Impact"),
                    ("MED", "Medium Impact"),
                    ("HIGH", "High Impact"),
                ],
                default="MED",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="hot_water",
            field=models.CharField(
                choices=[
                    ("LOW", "Low Impact"),
                    ("MED", "Medium Impact"),
                    ("HIGH", "High Impact"),
                ],
                default="MED",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="lights_electronics",
            field=models.CharField(
                choices=[
                    ("LOW", "Low Impact"),
                    ("MED", "Medium Impact"),
                    ("HIGH", "High Impact"),
                ],
                default="MED",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="long_trips",
            field=models.CharField(
                choices=[
                    ("LOW", "Low Impact"),
                    ("MED", "Medium Impact"),
                    ("HIGH", "High Impact"),
                ],
                default="MED",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="new_purchases",
            field=models.CharField(
                choices=[
                    ("LOW", "Low Impact"),
                    ("MED", "Medium Impact"),
                    ("HIGH", "High Impact"),
                ],
                default="MED",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="recycling",
            field=models.CharField(
                choices=[
                    ("LOW", "Low Impact"),
                    ("MED", "Medium Impact"),
                    ("HIGH", "High Impact"),
                ],
                default="MED",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="renewable_energy",
            field=models.CharField(
                choices=[
                    ("YES", "✅ Yes, mostly solar/green energy"),
                    ("SOME", "⚖️ Some renewables in the mix"),
                    ("NO", "❌ No, just standard grid"),
                ],
                default="SOME",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="short_trips",
            field=models.CharField(
                choices=[
                    ("LOW", "Low Impact"),
                    ("MED", "Medium Impact"),
                    ("HIGH", "High Impact"),
                ],
                default="MED",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="waste_amount",
            field=models.CharField(
                choices=[
                    ("LOW", "🟢 Less than a bin"),
                    ("MED", "🟡 About a bin"),
                    ("HIGH", "🔴 More than a bin"),
                ],
                default="MED",
                max_length=4,
            ),
            preserve_default=False,
        ),
    ]
