# Generated by Django 4.2.22 on 2025-09-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_remove_weeklycheckupresult_appliance_usage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="car_type",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="cooking_food",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="heating_cooling",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="hot_water",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="lights_electronics",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="long_trips",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="new_purchases",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="recycling",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="renewable_energy",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="short_trips",
        ),
        migrations.RemoveField(
            model_name="weeklycheckupresult",
            name="waste_amount",
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="appliance_usage",
            field=models.CharField(
                choices=[
                    ("OPT", "Full loads, eco settings"),
                    ("REG", "Regular loads"),
                    ("FREQ", "Frequent small loads"),
                    ("HEAVY", "Multiple loads daily"),
                ],
                default="REG",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="daily_transport",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Mostly walk/cycle"),
                    ("PUBLIC", "Mainly public transport"),
                    ("MIXED", "Mix of car and alternatives"),
                    ("CAR", "Primarily car"),
                ],
                default="MIXED",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="energy_source",
            field=models.CharField(
                choices=[
                    ("FULL_GREEN", "100% renewable/solar"),
                    ("PARTIAL", "Partial renewable mix"),
                    ("GREEN_OPT", "Green energy plan"),
                    ("STANDARD", "Standard grid power"),
                ],
                default="STANDARD",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="heating_usage",
            field=models.CharField(
                choices=[
                    ("OFF", "Didn't need it this week"),
                    ("ECO", "Used eco settings/timer"),
                    ("SOME", "A few hours when needed"),
                    ("MOST", "Most of the day"),
                ],
                default="SOME",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("NONE", "No car used"),
                    ("ELECTRIC", "Electric vehicle"),
                    ("HYBRID", "Hybrid/Small efficient car"),
                    ("STANDARD", "Standard car"),
                    ("LARGE", "Large vehicle/SUV"),
                ],
                default="STANDARD",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="waste_generation",
            field=models.CharField(
                choices=[
                    ("MINIMAL", "Minimal waste, mostly reusable"),
                    ("LOW", "Small bag, mostly recycled"),
                    ("MEDIUM", "Regular bin amount"),
                    ("HIGH", "Multiple bags/overflow"),
                ],
                default="MEDIUM",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="water_usage",
            field=models.CharField(
                choices=[
                    ("MINIMAL", "Quick showers, minimal usage"),
                    ("MODERATE", "Moderate usage, some conservation"),
                    ("TYPICAL", "Typical household usage"),
                    ("HIGH", "Extended usage, multiple daily"),
                ],
                default="TYPICAL",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="weekly_consumption",
            field=models.CharField(
                choices=[
                    ("NONE", "No new purchases"),
                    ("ESSENTIAL", "Only essentials"),
                    ("MODERATE", "Some non-essential items"),
                    ("HIGH", "Multiple large purchases"),
                ],
                default="MODERATE",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="weeklycheckupresult",
            name="weekly_travel",
            field=models.CharField(
                choices=[
                    ("LOCAL", "Stayed local (<20km)"),
                    ("REGION", "Regional trips (20-100km)"),
                    ("LONG", "Long distance (>100km)"),
                    ("FLIGHT", "Took a flight"),
                ],
                default="LOCAL",
                max_length=6,
            ),
        ),
    ]
